name: test

on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # required by codecov

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Doctest
        run: |
          python -m doctest *.py
